export const monthDayOptions = [
  { label: "1st", value: "First" },
  { label: "2nd", value: "Second" },
  { label: "3rd", value: "Third" },
  { label: "4th", value: "Fourth" },
  { label: "5th", value: "Fifth" },
  { label: "6th", value: "Sixth" },
  { label: "7th", value: "Seventh" },
  { label: "8th", value: "Eighth" },
  { label: "9th", value: "Ninth" },
  { label: "10th", value: "Tenth" },
  { label: "11th", value: "Eleventh" },
  { label: "12th", value: "Twelfth" },
  { label: "13th", value: "Thirteenth" },
  { label: "14th", value: "Fourteenth" },
  { label: "15th", value: "Fifteenth" },
  { label: "16th", value: "Sixteenth" },
  { label: "17th", value: "Seventeenth" },
  { label: "18th", value: "Eighteenth" },
  { label: "19th", value: "Nineteenth" },
  { label: "20th", value: "Twentieth" },
  { label: "21st", value: "TwentyFirst" },
  { label: "22nd", value: "TwentySecond" },
  { label: "23rd", value: "TwentyThird" },
  { label: "24th", value: "TwentyFourth" },
  { label: "25th", value: "TwentyFifth" },
  { label: "26th", value: "TwentySixth" },
  { label: "27th", value: "TwentySeventh" },
  { label: "28th", value: "TwentyEighth" },
  { label: "End of Month", value: "EndOfMonth" },
];
